package com.ibm.ecm.configmgr;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package freshcmui_gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
//import javax.swing.JOptionPane;
import java.io.File;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author 06269B744
 */
public class ProfDetails2 extends javax.swing.JFrame {

    /**
     * Creates new form ProfDetails
     */
    public ProfDetails2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ProfileName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        backBtn = new JButton();
        
        models[0] = new DefaultComboBoxModel<>(wasdb);
        models[1] = new DefaultComboBoxModel<>(wldb);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("IBM FileNet Fresh Profile Information");

        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanel1FocusLost(evt);
            }
        });

        jLabel2.setText("Profile Name:*");
        jLabel2.setToolTipText("Enter a name for your new profile. Use a name that will help you remember how this profile will be used. The profile name will be used as the directory name for storing the profile configuration and other configuration files. The name must be a valid directory name for your operating system, such as CEprofile1.");

        ProfileName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ProfileNameFocusLost(evt);
            }
        });
        ProfileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileNameActionPerformed(evt);
            }
        });
        ProfileName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ProfileNameKeyReleased(evt);
            }
        });

        jLabel3.setText("Directory name that will contain the new profile directory and files: * ");
        jLabel3.setToolTipText("Enter the absolute path to a directory where you want to store your new profile. \\n A profile subdirectory with your profile name will be created in this directory. \\n The new profile subdirectory will contain the configuration files that make up your profile. \\n If you enter a directory name that does not exist, the directory will be created for you.");

        jTextField2.setText("C:\\Program Files\\IBM\\FileNet\\ContentEngine\\tools\\configure\\profiles");

        jLabel4.setText("Application Server:*");
        jLabel4.setToolTipText("Application server selection (Websphere/WebLogic)");
        String servers[] = { "WebSphere Application Server", "WebLogic Application Server" };
        
        jComboBox1 = new JComboBox(servers);
       // jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WebSphere Application Server", "WebLogic Application Server" }));
        //jComboBox1.addItem("WebSphere Application Server");
        //jComboBox1.addItem("WebLogic Aplication Server");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        /*jComboBox1.addItemListener(new ItemListener() {
			@Override
			public void itemStateChanged(ItemEvent e) {
				// TODO Auto-generated method stub
				serverChanged(e);
			}
		});
		*/
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        
        backBtn.setText("Back");
        backBtn.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				backActionPerformed(e);
			}
		});

        jLabel5.setText("* denotes a required field");

        jSeparator4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel6.setText("Database Driver:*");
        jLabel6.setToolTipText("Database Driver Selection: Oracle, MSSQL, DB2");
        /*if(CMUtil.appServer.equalsIgnoreCase("WebSphere Application Server"))
        {
        	//System.out.println();
        	jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oracle", "Microsoft JDBC", "DB2", "Oracle (RAC)" }));
        }
        else if(CMUtil.appServer.equalsIgnoreCase("WebLogic Application Server"))
        {
        	jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oracle", "Microsoft JDBC", "DB2", "Oracle (RAC)","Oracle (SSL Enabled)" }));
        }
        else
        {
        	JOptionPane.showMessageDialog(rootPane, "Please select the application server !!!");
        }*/
        jComboBox2.setToolTipText("");
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton3.setText("Browse");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setText("LDAP Server:*");
        jLabel7.setToolTipText("");
        
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active Directory", "ADAM or AD LDS", "CA Directory", "eDirectory", "Oracle Internet Directory Server", "Oracle Directory Server Enterprise Edition", "Tivoli Directory Server", "Non-LDAP VMM" }));
        jComboBox3.setSelectedIndex(6);
        jComboBox3.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				jComboBox3ActionPerformed(e);
			}
		});

        jLabel8.setText("LDAP Repository Type:*");
        jLabel8.setToolTipText("");
        
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Federated repositories", "Stand-alone LDAP registry" }));
        jComboBox4.setToolTipText("");
        jLabel8.setEnabled(true);
        jComboBox4.setEnabled(true);
        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });
        
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel9.setText("Deployment Mode");
        jLabel9.setToolTipText("");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard", "ND", "Cluster" }));
        jComboBox5.setToolTipText("");
        jLabel9.setEnabled(true);
        jComboBox5.setEnabled(true);
        jComboBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox5ItemStateChanged(evt);
            }
        });
        
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jSeparator1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ProfileName, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(25, 25, 25)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(71, 71, 71))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBox3, 0, 328, Short.MAX_VALUE)
                                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProfileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                	.addComponent(backBtn)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(19, 19, 19))
        );

        jSeparator2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jSeparator3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    
    
    private void jPanel1FocusLost(java.awt.event.FocusEvent evt) {                                  
        // TODO add your handling code here:
    	
    }       
    
    private void jComboBox3ActionPerformed(ActionEvent evt) {
    	ldapServerType = jComboBox3.getSelectedItem().toString();
    	//CMUtil.ldapServerType = ldapServerType;
    	System.out.println(ldapServerType);
    	if(ldapServerType.equals("Active Directory"))
    		CMUtil.ldapServerType = "activedirectory";
    	else if(ldapServerType.equals("ADAM or AD LDS"))
    		CMUtil.ldapServerType = "adam";
    	else if(ldapServerType.equals("CA Directory"))
    		CMUtil.ldapServerType = "ca";
    	else if(ldapServerType.equals("eDirectory"))
    		CMUtil.ldapServerType = "edirectory";
    	else if(ldapServerType.equals("Oracle Internet Directory Server"))
    		CMUtil.ldapServerType = "oid";
    	else if(ldapServerType.equals("Oracle Directory Server Enterprise Edition"))
    		CMUtil.ldapServerType = "oracledirectorySE";
    	else if(ldapServerType.equals("Tivoli Directory Server"))
    		CMUtil.ldapServerType = "tivoli";
    	else if(ldapServerType.equals("Non-LDAP VMM"))
    		CMUtil.ldapServerType = "nonldapvmm";
    	else
    		System.out.println("Wrong selection");
    	System.out.println(CMUtil.ldapServerType);
    }

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	ldapRepoType = jComboBox4.getSelectedItem().toString();
    	//CMUtil.ldapRepoType = ldapRepoType;
    	System.out.println(ldapRepoType);
    	if(ldapRepoType.equals("Federated repositories"))
    		CMUtil.ldapRepoType = "federated";
    	else if(ldapRepoType.equals("Stand-alone LDAP registry"))
    		CMUtil.ldapRepoType = "Standalone";
    	else
    		System.out.println("Wrong selection");
    	System.out.println(CMUtil.ldapRepoType);
    }                                          

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        JFileChooser profPath = new JFileChooser();
        profPath.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        profPath.showOpenDialog(null);
        File profDir = profPath.getSelectedFile();
        if (!(profDir.isDirectory() && profDir.exists())) {
            profDir.mkdirs();
        }
        String profAPath = profDir.getAbsolutePath();
        jTextField2.setText(profAPath);

    }                                        

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	String dbType="";
    	dbType = jComboBox2.getSelectedItem().toString();
    	System.out.println(dbType);
    	if(dbType.equals("Oracle"))
    		CMUtil.dbType = "oracle";
    	else if(dbType.startsWith("Microsoft"))
    		CMUtil.dbType = "mssql";
    	else if(dbType.equals("DB2"))
    		CMUtil.dbType = "db2";
    	else if(dbType.equals("Oracle (RAC)"))
    		CMUtil.dbType = "orrac";
    	else
    		System.out.println("Wrong selection");
    	CMUtil.implementorID = CMUtil.dbType;
    }                                          

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    public void backActionPerformed(ActionEvent e) {
    	new NewJFrame("","").setVisible(true);
    	this.dispose();
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String str = ProfileName.getText().trim();
        if (str.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Profile cannot be empty. Please provide a valid name.");
            //jButton2.setEnabled(false);
        }
        else
        {
            CMUtil.profileName=str;
            JOptionPane.showMessageDialog(rootPane, str +" profile will be created.");
            //JOptionPane.showMessageDialog(rootPane, str);
            //SplitPanel obj= new SplitPanel(str);// obj created for class Second()
            //jButton2.setEnabled(true);
            if (appServer.equals("WebSphere Application Server")) {
	            new WAS_FreshProfile(appServer).setVisible(true);
	            this.dispose();
            }
            else if(appServer.equals("WebLogic Application Server")) {
            	WL_FreshProfile wl = new WL_FreshProfile(appServer);
            	wl.setVisible(true);
            	this.dispose();
            }
        }
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        System.exit(0);
    }                                        

    private void ProfileNameKeyReleased(java.awt.event.KeyEvent evt) {                                        
        // TODO add your handling code here:
        //jLabel7.setText("");
    }                                       

    private void ProfileNameActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        //obj.setJTreeDynamically(str);//Execute the method my_update to pass str
    }                                           

    private void ProfileNameFocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
        if (ProfileName.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "A profile name is required.");
            ProfileName.requestFocusInWindow();
        }
    }                                     

    private void jComboBox5ItemStateChanged(java.awt.event.ItemEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	String deployMode = jComboBox5.getSelectedItem().toString();
    	System.out.println(deployMode);
    	if(deployMode.equals("Standard"))
    		CMUtil.deployMode = "standard";
    	else if(deployMode.equals("ND"))
    		CMUtil.deployMode = "netdeploy";
    	else if(deployMode.equals("Cluster"))
    		CMUtil.deployMode = "cluster";
    	else
    		System.out.println("Wrong selection");
    	System.out.println(CMUtil.deployMode);
    }                                          

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	appServer = jComboBox1.getSelectedItem().toString();
       if (appServer.equals("WebSphere Application Server")) {
        	jLabel9.setEnabled(true);
        	jComboBox5.setEnabled(true);
            jLabel8.setEnabled(true);
            jComboBox4.setEnabled(true);
        }
        else if(appServer.equals("WebLogic Application Server"))
        {
        	jLabel8.setEnabled(false);
        	jComboBox4.setEnabled(false);
            jLabel9.setEnabled(false);
            jComboBox5.setEnabled(false);
        }
        CMUtil.appServer = appServer;
        System.out.println(CMUtil.appServer);
        /*if(CMUtil.appServer.equalsIgnoreCase("WebSphere Application Server"))
        {
        	//System.out.println();
        	jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oracle", "Microsoft JDBC", "DB2", "Oracle (RAC)" }));
        }
        else if(CMUtil.appServer.equalsIgnoreCase("WebLogic Application Server"))
        {
        	jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oracle", "Microsoft JDBC", "DB2", "Oracle (RAC)","Oracle (SSL Enabled)" }));
        }
        else
        {
        	JOptionPane.showMessageDialog(rootPane, "Please select the application server !!!");
        }*/
    	int i = jComboBox1.getSelectedIndex();
        jComboBox2.setModel(models[i]);
    }                                         

    public void serverChanged(ItemEvent ev)
    {
    	if(ev.getSource()==jComboBox1)
		{
			appServer = jComboBox1.getSelectedItem().toString();
			System.out.println(appServer);
			//jComboBox1.removeAllItems();
			 if (appServer.equals("WebSphere Application Server")) {
				 
		        	jLabel9.setEnabled(true);
		        	jComboBox5.setEnabled(true);
		            jLabel8.setEnabled(true);
		            jComboBox4.setEnabled(true);
		            jComboBox2.removeAllItems();
		            for(int i=0;i<wasdb.length;i++)
		            {
		            	jComboBox2.addItem(wasdb[i]);
		            }
			 }
			 else if(appServer.equals("WebLogic Application Server"))
		        {
		        	jLabel8.setEnabled(false);
		        	jComboBox4.setEnabled(false);
		            jLabel9.setEnabled(false);
		            jComboBox5.setEnabled(false);
		            jComboBox2.removeAllItems();
		            for(int i=0;i<wldb.length;i++)
		            {
		            	jComboBox2.addItem(wldb[i]);
		            }
		        }
			 else
				 System.out.println("Not selected");
		    CMUtil.appServer = appServer;
			System.out.println(CMUtil.appServer);
		}
    }
    public String getProfName() {
        return ProfileName.getText();
    }
    
    public String dbtype () {
        String dbtype = jComboBox2.getSelectedItem().toString();
        return dbtype;
    }
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfDetails2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfDetails2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfDetails2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfDetails2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfDetails2().setVisible(true);
            }
        });*/
   // }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField ProfileName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private JButton backBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    public javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField2;
    private String appServer;
    private String ldapRepoType;
    private String ldapServerType;
    public String wasdb[] = { "Oracle", "Microsoft JDBC", "DB2", "Oracle (RAC)" };
    public String wldb[] = { "Oracle", "Microsoft JDBC", "DB2", "Oracle (RAC)" };
    private ComboBoxModel[] models = new ComboBoxModel[2];
    // End of variables declaration                   
}
